CommandSet EvilModCastleWallCommandSet
1 = Command_StartSelfRepair
End


CommandSet RohanEconomyPlotCommandSet
  1  = Command_UnpackExplicitRohanFarm
  2  = Command_ConstructEntMoot
End

CommandSet MordorEconomyPlotCommandSet
  1  = Command_UnpackExplicitMordorLumbermill
  2  = Command_UnpackExplicitMordorSlaughterhouse
End
CommandSet IsengardEconomyPlotCommandSet
  1  = Command_UnpackExplicitIsengardLumbermill
  2  = Command_UnpackExplicitIsengardFurnace
End
CommandSet GoblinEconomyPlotCommandSet
  1  = Command_UnpackExplicitWildLumbermill
  2  = Command_UnpackExplicitWildMineShaft	;Command_ConstructGoblinCave
End
CommandSet AngmarEconomyPlotCommandSet
  1  = Command_UnpackExplicitIsengardLumbermill
  2  = Command_UnpackExplicitAngmarMill
End
CommandSet MenEconomyPlotCommandSet
  1  = Command_UnpackExplicitRohanFarm
  
End
CommandSet ArnorEconomyPlotCommandSet
  1  = Command_UnpackExplicitGondorFarm
 
End
CommandSet ElfEconomyPlotCommandSet
  1  = Command_UnpackExplicitElvenMallornTree
  
End
CommandSet DwarfEconomyPlotCommandSet
  1  = Command_UnpackExplicitDwarvenMineShaft
End




CommandSet BFME1GondorFoundationCommandSet
	1  = Command_ConstructGondorFarm
	2  = Command_ConstructGondorBlackSmith
	3  = Command_ConstructGondorBarracks
	4  = Command_ConstructGondorArcherRange
	5  = Command_ConstructGondorStatue
	6  = Command_ConstructGondorWell
	7  = Command_ConstructGondorKeep
	8  = Command_ConstructGondorStable
	9  = Command_ConstructGondorWorkshop
	10 = Command_ConstructGondorMarketPlace
End

CommandSet BFME1RohanFoundationCommandSet
	1  = Command_ConstructRohanFarm 
	2  = Command_ConstructRohanBarracks 
	3  = Command_ConstructRohanArcherRange 
	4  = Command_ConstructRohanStatue 
	5  = Command_ConstructRohanWell 
	6  = Command_ConstructRohanStable 
	7  = Command_ConstructRohanArmory 
End

CommandSet BFME1ElvesFoundationCommandSet
	1  = Command_ConstructElvenMallornTree 
	2  = Command_ConstructElvenBarracks 
	3  = Command_ConstructElvenStatue 
	4  = Command_ConstructElvenMirrorOfGaladriel 
	5  = Command_ConstructElvenWatchTower 
	6  = Command_ConstructElvenGreenPasture 
	7  = Command_ConstructEregionForge 
End

CommandSet BFME1DwarvesFoundationCommandSet
	1  = Command_ConstructDwarvenMineShaft 
	2  = Command_ConstructDwarvenBarracks 
	3  = Command_ConstructDwarvenArcheryRange 
	4  = Command_ConstructDwarvenStatue 
	5  = Command_ConstructDwarvenHearth 
	6  = Command_ConstructDwarvenSentryTower 
	7  = Command_ConstructDwarvenForgeWorks 
End

CommandSet BFME1ArnorFoundationCommandSet
	1  = Command_ConstructArnorFarm 
	2  = Command_ConstructArnorBarracks 
	3  = Command_ConstructArnorArcherRange 
	4  = Command_ConstructArnorStable 
	5  = Command_ConstructArnorElvenBarracks  
	6  = Command_ConstructArnorBlackSmith 
	7  = Command_ConstructArnorStatue 
	8  = Command_ConstructArnorWell 
	9  = Command_ConstructArnorKeep 
	10 = Command_ConstructArnorWorkshop 
	11 = Command_ConstructArnorMarketPlace 
End

CommandSet BFME1MordorFoundationCommandSet
	1  = Command_ConstructMordorSlaughterHouse 
	2  = Command_ConstructMordorOrcPit 
	3  = Command_ConstructMordorUrukTent 
	4  = Command_ConstructMordorBattleTower 
	5  = Command_ConstructMordorTrollCage 
	6  = Command_ConstructMordorSiegeWorks 
	7  = Command_ConstructMordorArmory 
End

CommandSet BFME1IsnegardFoundationCommandSet
	1  = Command_ConstructIsengardFurnace 
	2  = Command_ConstructIsengardTavern 
	3  = Command_ConstructIsengardUrukPit 
	4  = Command_ConstructIsengardWargSentry 
	5  = Command_ConstructIsengardBattleTower 
	6  = Command_ConstructIsengardWargPit 
	7  = Command_ConstructIsengardSiegeWorks 
	8  = Command_ConstructIsengardArmory 
End

CommandSet BFME1WildFoundationCommandSet
	1  = Command_ConstructWildMineShaft 
	2  = Command_ConstructGoblinCave 
	3  = Command_ConstructGoblinFissure 
	4  = Command_ConstructWildSentryTower 
	5  = Command_ConstructWildSpiderPit 
	6  = Command_ConstructWildTreasureTrove 
End

CommandSet BFME1EvilMenFoundationCommandSet
	1  = Command_ConstructEasterlingWindMill 
	2  = Command_ConstructHaradFarm 
	3  = Command_ConstructEvilMenEasterlingBarracks 
	4  = Command_ConstructMordorHaradrimPalace 
	5  = Command_ConstructMordorTavern 
	6  = Command_constructEvilMenEasterlingStablesBuilding 
	7  = Command_ConstructEvilMenHaradrimStables 
	8  = Command_ConstructRhunArmory 
	9  = Command_ConstructHaradArmory 
	10 = Command_constructEasterlingBattleTower 
	11 = Command_constructHaradWatchTower 
	12 = Command_ConstructEvilMenStatue 
	13 = Command_ConstructMumakilPen 
	14 = Command_constructEvilMenSorcererBuilding 
End

CommandSet BFME1RhunFoundationCommandSet
	1  = Command_ConstructEasterlingWindMill 
	2  = Command_ConstructEvilMenEasterlingBarracks 
	3  = Command_ConstructMordorTavern 
	4  = Command_constructEvilMenEasterlingStablesBuilding 
	5  = Command_ConstructRhunArmory 
	6  = Command_constructEasterlingBattleTower 
	7  = Command_constructEvilMenSorcererBuilding 
End

CommandSet BFME1HaradFoundationCommandSet
	1  = Command_ConstructHaradFarm 
	2  = Command_ConstructMordorHaradrimPalace 
	3  = Command_ConstructMordorTavern 
	4  = Command_ConstructHaradArmory 
	5  = Command_constructHaradWatchTower 
	6  = Command_ConstructEvilMenStatue 
	7  = Command_ConstructMumakilPen 
End

CommandSet BFME1AngmarFoundationCommandSet
	1  = Command_ConstructAngmarMill 
	2  = Command_ConstructAngmarBarracks 
	3  = Command_ConstructAngmarHallofTwilight 
	4  = Command_ConstructAngmarSentryTower 
	5  = Command_ConstructAngmarDen 
	6  = Command_ConstructAngmarForgeWorks 
End

CommandSet BFME1ArnorPorterCommandSet
	1  = Command_Stop
	2  = Command_PorterExtinguishFire
	3  = Command_PorterConstructArnorFarm
	4  = Command_PorterConstructArnorBarracks
	5  = Command_PorterConstructArnorElvenBarracks
	6  = Command_PorterConstructArnorArcheryRange
	7  = Command_PorterConstructArnorStable
	8  = Command_PorterConstructArnorWorkshop
	9  = Command_PorterConstructArnorSentryTower
	10 = Command_PorterConstructArnorWell
	11 = Command_PorterConstructArnorStatue
	12 = Command_PorterConstructArnorBlacksmith
	13 = Command_UpgradeValinorMode
End

CommandSet BFME1ElvenPorterCommandSet   
	1  = Command_Stop
	2  = Command_PorterExtinguishFire   
	3  = Command_PorterConstructElvenMallornTree
	4  = Command_PorterConstructElvenBarracks
	5  = Command_PorterConstructElvenGreenPasture
	6  = Command_PorterConstructElvenLoreMasterShrine 
	7  = Command_PorterConstructElvenEntMoot
	8  = Command_PorterConstructElvenStatue
	9  = Command_PorterConstructElvenWatchTower
	10 = Command_PorterConstructElvenMirrorOfGaladriel   
	11 = Command_PorterConstructEregionForge
	12 = Command_UpgradeValinorMode
End

CommandSet BFME1AngmarPorterCommandSet
   	1  = Command_Stop
   	2  = Command_PorterExtinguishFire
   	3  = Command_PorterConstructAngmarMill
   	4  = Command_PorterConstructAngmarBarracks
   	5  = Command_PorterConstructAngmarDen
   	6  = Command_PorterConstructAngmarHallofTwilight
   	7  = Command_PorterConstructAngmarForgeWorks
   	8  = Command_PorterConstructAngmarSentryTower
	9  = Command_UpgradeAngabadMode
End

CommandSet BFME1MenPorterCommandSet 
	1  = Command_Stop
	2  = Command_PorterExtinguishFire
	3  = Command_PorterConstructMenFarm
	4  = Command_PorterConstructMenBarracks
	5  = Command_PorterConstructMenArcheryRange
	6  = Command_PorterConstructMenStable
	7  = Command_PorterConstructMenWorkshop
	8  = Command_PorterConstructMenSentryTower
	9  = Command_PorterConstructMenWell
	10 = Command_PorterConstructMenStatue
	11 = Command_PorterConstructMenBlacksmith
	12 = Command_PorterConstructMenMarketPlace
	13 = Command_UpgradeValinorMode
End

CommandSet BFME1DwarvenPorterCommandSet
	1  = Command_Stop
	2  = Command_PorterExtinguishFire
	3  = Command_PorterConstructDwarvenMineShaft
	4  = Command_PorterConstructDwarvenBarracks
	5  = Command_PorterConstructDwarvenArcheryRange 
	6  = Command_PorterConstructDwarvenForgeWorks
	7  = Command_PorterConstructDwarvenSentryTower
	8  = Command_PorterConstructDwarvenHearth
	9  = Command_PorterConstructDwarvenStatue
	10 = Command_UpgradeValinorMode
End

CommandSet BFME1WildPorterCommandSet
	1  = Command_Stop
	2  = Command_PorterExtinguishFire
	3  = Command_PorterConstructWildMineShaft
	4  = Command_PorterConstructWildLumberMill
	5  = Command_PorterConstructWildCave
	6  = Command_PorterConstructWildSpiderPit
	7  = Command_PorterConstructWildFissure  
	8  = Command_PorterConstructWildSentryTower
	9  = Command_PorterConstructWildTreasureTrove
End

CommandSet BFME1IsengardPorterCommandSet
	1  = Command_Stop
	2  = Command_PorterExtinguishFire
	3  = Command_PorterConstructIsengardFurnace
	4  = Command_PorterConstructIsengardLumberMill
	5  = Command_PorterConstructIsengardTavern
	6  = Command_PorterConstructIsengardUrukPit
	7  = Command_PorterConstructIsengardWargPit
	8  = Command_PorterConstructIsengardSiegeWorks
	9  = Command_PorterConstructIsengardBattleTower
	10  = Command_PorterConstructIsengardWargSentry
	11 = Command_PorterConstructIsengardArmory
	12 = Command_UpgradeAngabadMode
End

CommandSet BFME1MordorPorterCommandSet
	1  = Command_Stop
	2  = Command_PorterExtinguishFire
	3  = Command_PorterConstructMordorSlaughterHouse
	4  = Command_PorterConstructMordorLumberMill
	5  = Command_PorterConstructMordorOrcPit
	6  = Command_PorterConstructMordorUrukTent  
	7  = Command_PorterConstructMordorTrollCage
	8  = Command_PorterConstructMordorArmory 
	9  = Command_PorterConstructMordorSiegeWorks
	10 = Command_PorterconstructMordorBattleTower
	11 = Command_PorterconstructMordorBarricadePurchased 
	12 = Command_UpgradeAngabadMode
End

CommandSet BFME1GondorFortressCommandSet
	InitialVisible = 7 
	//Main Menu
	2   	= Command_SelectRevivablesMenFortress 
	3   	= Command_SelectUpgradesMenFortress 
	4	= Command_SpecialAbilityIvoryTowerVision 
	5	= Command_FireWeaponMenFortressBoilingOil 

	//Upgrades Menu
	8	= Command_PurchaseUpgradeMenFortressBanners 
	9	= Command_PurchaseUpgradeMenFortressHouseOfHealing 
	10	= Command_PurchaseUpgradeMenFortressIvoryTower 
	11	= Command_PurchaseUpgradeMenFortressBoilingOil 
	12	= Command_PurchaseUpgradeMenFortressNumenorStonework 
	13	= Command_PurchaseUpgradeMenFortressFlamingMunitions 
	14	= Command_RadialBack

	//Hero Menu
	16	= Command_RingHeroReviveSlot 
	17	= Command_CreateAHeroReviveSlot 
	18	= Command_GenericReviveSlot1 
	19	= Command_GenericReviveSlot2 
	20	= Command_GenericReviveSlot3 
	21	= Command_GenericReviveSlot4 
	22	= Command_GenericReviveSlot5 
	23	= Command_GenericReviveSlot6 
	24	= Command_GenericReviveSlot7 
	25	= Command_GenericReviveSlot8 
	26	= Command_GenericReviveSlot9 
	27	= Command_GenericReviveSlot10 
	28	= Command_GenericReviveSlot11 
	29	= Command_GenericReviveSlot12 
	30	= Command_GenericReviveSlot13 
	31	= Command_GenericReviveSlot14 
	32	= Command_GenericReviveSlot15 
	33	= Command_RadialBack 
End

CommandSet BFME1RohanFortressCommandSet
	InitialVisible = 7
	//Main Menu
	2   	= Command_SelectRevivablesRohanFortress 
	3   	= Command_SelectUpgradesRohanFortress 
	4	= Command_SpellBookCloudBreakRohanHorn
	5	= Command_SpellBookDraft

	//Upgrades Menu
	8	= Command_PurchaseUpgradeRohanFortressBanners
	9	= Command_PurchaseUpgradeRohanFortressSiegeKegs 
	10	= Command_PurchaseUpgradeRohanDraft
	11	= Command_PurchaseUpgradeRohanFortressFlamingMunitions 
	12	= Command_PurchaseUpgradeRohanFortressNumenorStonework
	13	= Command_PurchaseUpgradeRohanHammerhandHorn 
	14	= Command_RadialBack

	//Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot	
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1DwarvenFortressCommandSet
	InitialVisible = 7
	//Main Menu
	2	= Command_FireWeaponDwarvenFortressOilCasks
	3   	= Command_SelectRevivablesDwarvenFortress
	4   	= Command_SelectUpgradesDwarvenFortress
	5	= Command_FireWeaponMightyCatapult

	//Upgardes Menu
	8	= Command_PurchaseUpgradeDwarvenFortressBanners
	9	= Command_PurchaseUpgradeDwarvenFortressSiegeKegs
	10	= Command_PurchaseUpgradeDwarvenFortressFlamingMunitions
	11	= Command_PurchaseUpgradeDwarvenFortressOilCasks
	12	= Command_PurchaseUpgradeDwarvenFortressDwarvenStonework
	13	= Command_PurchaseUpgradeDwarvenFortressMightyCatapult
	14	= Command_RadialBack
	
	//Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot				// Note we also need an extra slot for the Create A Hero
	18	= Command_GenericReviveSlot1				//Revives any hero. keep them UNIQUE within the same commandset! 
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1ElvenFortressCommandSet
	InitialVisible = 7
	//Main Menu
	2   	= Command_SelectRevivablesElvenFortress
	3	= Command_SelectUpgradesElvenFortress
	4	= Command_PurchaseNewEagle
	
		//Improvements
	8       = Command_PurchaseUpgradeElvenFortressEnchantedAnvil
	9	= Command_PurchaseUpgradeElvenFortressMysticFountains
	10	= Command_PurchaseUpgradeElvenFortressBlessedMist
	11	= Command_PurchaseUpgradeElvenFortressCrystalMoat
	12	= Command_PurchaseUpgradeElvenFortressEncasingVines
	13	= Command_PurchaseUpgradeElvenFortressEaglesNest
	14	= Command_RadialBack
	
	//Heroes
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot				// Note we also need an extra slot for the Create A Hero
	18	= Command_GenericReviveSlot1				// Revives any hero. keep them UNIQUE within the same commandset! 
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1ArnorFortressCommandSet
	InitialVisible = 7
	; Main Menu
	2   	= Command_SelectRevivablesArnorFortress
	3   	= Command_SelectUpgradesArnorFortress
;	4	= 
;	5	= 

	; Upgrades Menu
	8	= Command_PurchaseUpgradeArnorFortressBanners
	9	= Command_PurchaseUpgradeArnorFortressHouseOfHealing
;	10	= 
;	11	= 
	12	= Command_PurchaseUpgradeArnorFortressNumenorStonework
	13	= Command_PurchaseUpgradeArnorFortressFlamingMunitions
	14	= Command_PurchaseUpgradeArnorIstariUpgrades
	15	= Command_RadialBack

	; Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1WildFortressCommandSet
	InitialVisible = 7
	//Main Menu
	2   	= Command_SelectRevivablesWildFortress
	3   	= Command_SelectUpgradesWildFortress
	4   	= Command_PurchaseNewFireDrake	

	//Upgrades Menu
	8	= Command_PurchaseUpgradeWildFortressBatCloud
	9	= Command_PurchaseUpgradeWildFortressRazorSpines
	10	= Command_PurchaseUpgradeWildFortressFireArrows
	11	= Command_PurchaseUpgradeWildFortressWebCocoon
	12	= Command_PurchaseUpgradeWildFortressDragonNest	
	13	= Command_SpecialAbilityBatCloud
	14	= Command_RadialBack

	//Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1MordorFortressCommandSet
	InitialVisible = 6
	//Main Menu
	2	= Command_SelectRevivablesMordorFortress
	3	= Command_SelectUpgradesMordorFortress
	4	= Command_FireWeaponMordorFortressMagmaCauldrons
	5	= Command_FireWeaponMordorFortressSpireFireball

		//Upgrades Menu
	7	= Command_PurchaseUpgradeMordorFortressDoomPyres
	8	= Command_PurchaseUpgradeMordorFortressLavaMoat
	9	= Command_PurchaseUpgradeMordorFortressFireArrows
	10	= Command_PurchaseUpgradeMordorFortressMagmaCauldrons
	11	= Command_PurchaseTechnologyMordorFellbeasts 
	12	= Command_PurchaseUpgradeMordorFortressMordorEngineering 
	13	= Command_PurchaseUpgradeMordorFortressMorgulSorcery
	14	= Command_PurchaseUpgradeMordorFortressGorgorothSpire
	15	= Command_RadialBack

	//Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1IsengardFortressCommandSet
	InitialVisible	= 7
	//Main menu can select heroes, upgrades sub menus, or build a porter.
	2	= Command_SelectRevivablesIsengardFortress
	3	= Command_SelectUpgradesIsengardFortress
	4	= Command_IsengardWizardsTowerLightningStrike	
	
		//Improvements
	8	= Command_PurchaseUpgradeIsengardFortressMurderOfCrows
	9	= Command_PurchaseUpgradeIsengardFortressBurningForges
	10	= Command_PurchaseUpgradeIsengardFortressExcavations
	11	= Command_PurchaseUpgradeIsengardFortressOrcfireMunitions
	12	= Command_PurchaseUpgradeIsengardFortressIronPlating
	13	= Command_PurchaseUpgradeIsengardFortressWizardsTower
	14	= Command_SpecialAbilityMurderOfCrows
	15	= Command_RadialBack

	//Heroes
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1AngmarFortressCommandSet
	InitialVisible = 7
	//Main Menu
	2	= Command_SelectRevivablesAngmarFortress
	3   	= Command_SelectUpgradesAngmarFortress
	4	= Command_FireWeaponAngmarFortressSanctumFrostball

	//Upgardes Menu
	8	= Command_PurchaseUpgradeAngmarFortressBanners
	9	= Command_PurchaseUpgradeAngmarFortressSpikes
	10	= Command_PurchaseUpgradeAngmarFortressIceMunitions
	11	= Command_PurchaseUpgradeAngmarFortressHouseOfLamentation
	12	= Command_PurchaseUpgradeAngmarFortressIceWalls
	13	= Command_PurchaseUpgradeAngmarFortressSanctum
	14	= Command_RadialBack						; RotWK
	
	//Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End

CommandSet BFME1EasterlingFortressCommandSet
	InitialVisible = 7

	2	= Command_SelectRevivablesEasterlingFortress 
	3	= Command_SelectUpgradesEasterlingFortress 

		//Upgrades Menu
	8	= Command_PurchaseUpgradeEasterlingFortressBanner 
	9	= Command_PurchaseUpgradeEasterlingFortressBarbedArrows 
	10	= Command_PurchaseUpgradeEasterlingFortressSanctuary 
	11	= Command_PurchaseUpgradeEasterlingFortressReinforced 
	12	= Command_RadialBack

	//Hero Menu
	16	= Command_RingHeroReviveSlot
	17	= Command_CreateAHeroReviveSlot
	18	= Command_GenericReviveSlot1
	19	= Command_GenericReviveSlot2
	20	= Command_GenericReviveSlot3
	21	= Command_GenericReviveSlot4
	22	= Command_GenericReviveSlot5
	23	= Command_GenericReviveSlot6
	24	= Command_GenericReviveSlot7
	25	= Command_GenericReviveSlot8
	26	= Command_GenericReviveSlot9
	27	= Command_GenericReviveSlot10
	28	= Command_GenericReviveSlot11
	29	= Command_GenericReviveSlot12
	30	= Command_GenericReviveSlot13
	31	= Command_GenericReviveSlot14
	32	= Command_GenericReviveSlot15
	33	= Command_RadialBack
End